apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: kustom
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
        - name: app
          image: foo/bar:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # resources: {}
          resources: 
            limits:
              cpu: "1"
            requests:
              cpu: 250m